services:
  vinyl_store:
    image: mysql:latest
    container_name: vinyl-db
    environment:
      MYSQL_DATABASE: vinyl_store
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
